apiVersion: v1
kind: Pod
metadata:
  name: lifecycle-running-pod
  labels:
    lifecycle: running
spec:
  containers:
  - name: nginx
    image: nginx:alpine
    ports:
    - containerPort: 80
    livenessProbe:
      httpGet:
        path: /
        port: 80
      initialDelaySeconds: 3
      periodSeconds: 5
