apiVersion: v1
kind: Secret
metadata:
  name: {{ include "webapp.fullname" . }}-secret
  labels:
    {{- include "webapp.labels" . | nindent 4 }}
type: Opaque
stringData:
  API_KEY: {{ .Values.appSecrets.apiKey | quote }}
  JWT_SECRET: {{ .Values.appSecrets.jwtSecret | quote }}
