apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gitops-webapp-production
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: 'https://github.com/ponnaganti24bcs10350-svg/devops-assignment5.git'
    targetRevision: main
    path: monitoring-observability-gitops/03-gitops/apps/webapp
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
