apiVersion: v1
kind: Secret
metadata:
  name: app-secret
  namespace: default
type: Opaque
stringData:
  DB_PASSWORD: "SuperSecretPassword123!"
  API_KEY: "ak_live_998877665544332211"
  JWT_SECRET: "my-ultra-secure-jwt-signing-key"
  secret.key: |
    -----BEGIN RSA PRIVATE KEY-----
    MIIEowIBAAKCAQEA0Y3wZ...EXAMPLE_KEY_DATA...
    -----END RSA PRIVATE KEY-----
