apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-clusterip
  labels:
    app: app-clusterip
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app-clusterip
  template:
    metadata:
      labels:
        app: app-clusterip
    spec:
      containers:
      - name: nginx
        image: nginx:alpine
        command: ["/bin/sh", "-c", "echo '<h1>Response from ClusterIP Service Backend</h1>' > /usr/share/nginx/html/index.html && nginx -g 'daemon off;'"]
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: my-clusterip-service
spec:
  type: ClusterIP
  selector:
    app: app-clusterip
  ports:
  - port: 80
    targetPort: 80
